INSERT INTO USUARIO(nome, email, senha) VALUES('Aluno', 'aluno@email.com', '$2a$10$Yl8j451ln.priK3aNkeeYuPs/FEYYqK9aLAYp60zf7947rGF5qKJy');
INSERT INTO CONTATO(nome, email, campanha) VALUES('Marlon Pestana', 'marlon.pestana@email.com.br','PPL - Review Code');
INSERT INTO CONTATO(nome, email, campanha) VALUES('Carlina ferreira', 'kakazinha@email.com.br','PPL - Review Code');
INSERT INTO CONTATO(nome, email, campanha) VALUES('Joao Silva', 'joaosilva@email.com.br','PPL - Review Code');
INSERT INTO CONTATO(nome, email, campanha) VALUES('Maria joana', 'maria.joana@email.com.br','PPL - Review Code');

INSERT INTO CONTATO (nome,email,campanha) VALUES ('Logan I. Avila','pharetra.sed@loremutaliquam.net','Ornare LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lareina L. Payne','Nunc@eteuismodet.ca','Odio Auctor Institute');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Sierra Z. Giles','mi@aliquet.ca','Magna Ut Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Dane E. Mathews','Sed.congue.elit@primisin.com','Orci Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Allen Z. Gilmore','a@sedest.co.uk','Elit Nulla Facilisi PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Judah N. Charles','est.mollis@ligulaAeneangravida.org','Posuere Vulputate Lacus Limited');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Mona B. Cantrell','accumsan.interdum.libero@odiosagittissemper.edu','Feugiat Nec Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Sade R. Golden','magna.a@CuraeDonec.edu','Vehicula Pellentesque Tincidunt Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Brendan I. Haney','tincidunt.orci@utodiovel.co.uk','Dapibus LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Jessamine G. Lee','euismod@arcu.net','Sit Amet Lorem LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Rowan W. Vazquez','massa.lobortis.ultrices@etultricesposuere.co.uk','Morbi Tristique PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lamar O. Whitfield','In.ornare.sagittis@urnaetarcu.com','Tellus Nunc Lectus Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Carlos Z. Smith','arcu.eu@portaelita.ca','Est Associates');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Stella E. Barnes','molestie@ultricesDuis.org','Non Cursus Non Institute');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Emmanuel J. Vincent','natoque@liberoet.com','Nascetur Ridiculus LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Irma C. Coleman','eu@duisemperet.net','Orci Lobortis Augue LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Blake C. Banks','ut@atiaculisquis.net','Erat Volutpat Nulla Industries');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Ciaran O. Peck','pede.ultrices@pedeCras.co.uk','Sagittis Augue Eu Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Keaton W. Byrd','ipsum.Suspendisse.sagittis@nec.net','Nullam Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Akeem C. Ferguson','elit@atiaculisquis.com','Lacinia PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Hunter U. Jordan','Integer.vulputate@laoreetipsum.ca','Vel Convallis LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Carissa A. Macdonald','Integer@mauris.edu','Egestas Hendrerit Neque Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Quamar M. Rowe','elit.Etiam@loremsemperauctor.net','Ut Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Anthony E. Norman','posuere@Classaptent.net','Magna Malesuada Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Signe V. Larson','tellus.justo@acmi.com','Enim Mi Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Nasim I. Mendez','auctor.nunc.nulla@convallisconvallis.org','Vulputate Limited');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Yoshio S. Dixon','Donec@Aeneanmassa.edu','Lacinia Vitae Sodales Associates');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Fleur Y. Chavez','Nunc.sed@convallisest.ca','Curae; Phasellus Ornare PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Keelie K. Baird','ac.facilisis.facilisis@egetipsumDonec.ca','Tempus Risus Donec Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Zia X. Mclaughlin','a.malesuada.id@pede.ca','Eu Placerat Industries');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Yolanda L. House','a.feugiat.tellus@Vivamusnibh.co.uk','Cras Vehicula PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lester T. Rodriguez','nonummy.ultricies@tincidunt.co.uk','Sit Amet Lorem Associates');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Clare M. Mckay','adipiscing@augueac.edu','Faucibus Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Coby E. Little','adipiscing.fringilla@mauris.ca','Vehicula Et Rutrum Associates');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Demetrius K. Patterson','Donec.tempor@feugiatmetus.co.uk','Natoque Institute');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Alec U. Acosta','felis@habitantmorbi.com','Scelerisque Sed Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Ian S. Skinner','vestibulum@sapienCrasdolor.edu','Libero LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Angela Y. Wood','turpis.egestas.Fusce@nonlobortis.ca','Montes Nascetur Ridiculus LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Tanya U. Noel','mauris.Morbi.non@sedpede.org','Tristique Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Myles L. Joseph','vel.vulputate@Donecdignissimmagna.net','Cras Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Robert C. Sargent','ac@duinecurna.org','Nonummy PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Virginia G. Gardner','euismod.ac.fermentum@feugiatnecdiam.edu','Aliquam Eu PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Jason X. Mason','facilisis.eget.ipsum@eteuismodet.ca','Sem Elit Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Yvette W. Sutton','Suspendisse@tacitisociosqu.ca','Diam Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Aaron Z. Morales','nonummy.ac@pede.net','Ante Dictum Cursus LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Griffith O. Valentine','vulputate.lacus@molestie.net','Mauris Eu Elit Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Elizabeth E. Bass','dui.in@Duiscursus.com','Ut Cursus Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Erich L. Hanson','nibh@arcuVivamussit.edu','Ornare Egestas Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Castor W. Slater','Vivamus.nibh.dolor@accumsaninterdumlibero.com','Lectus Ante Dictum Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Byron P. Coffey','Morbi@Integervitaenibh.net','Lorem Eu Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Damian Q. Neal','ut.cursus.luctus@justosit.net','Tincidunt Associates');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Amanda X. York','elementum@vel.co.uk','Proin Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Hadassah R. Mccall','condimentum.Donec@nostraperinceptos.edu','Ut Odio Vel Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lenore E. Reeves','Ut@adipiscing.org','Convallis LLP');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Stacy M. Lester','id@dictumeuplacerat.com','Ipsum Porta Elit Company');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Madeline Y. Walsh','vestibulum@congueInscelerisque.com','Cursus Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Julian N. Hunt','volutpat.ornare.facilisis@Etiam.net','Ut LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Colin J. Morin','aliquam.iaculis@SedmolestieSed.net','Aliquet Nec Imperdiet Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Leonard D. Cole','Morbi@neccursus.ca','Mauris Sapien Cursus Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Dieter X. Kirkland','Cras@semelit.co.uk','Aptent Taciti Sociosqu Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Simon B. Mckee','neque.tellus@eratvolutpatNulla.net','Rutrum PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Marvin A. Flores','Quisque@aliquamarcuAliquam.edu','Ac Sem Ut LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Matthew A. Heath','scelerisque.scelerisque@laoreet.com','Eros Proin Company');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Karen B. Wheeler','ac@quamquis.org','Pharetra Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Byron R. Mcpherson','orci.in@blanditviverra.net','Nulla Magna Malesuada Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Aretha G. Pacheco','Nunc.ullamcorper.velit@etnetus.net','Nisl Sem Consequat Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Dustin I. Harris','elit.erat@atiaculisquis.ca','Convallis Ligula Donec PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Noble G. Flynn','mollis.lectus.pede@tempusnonlacinia.edu','Venenatis LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Austin Y. Meadows','nibh@dapibus.edu','Eu Eros Nam Limited');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Quinlan T. Ingram','vitae@metussit.org','Leo Morbi Industries');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Xyla W. Stevenson','augue.ac@liberolacusvarius.ca','Quam Dignissim Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Ira O. Cervantes','Cras@nonsapien.org','Libero Mauris Aliquam Limited');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lareina M. Rhodes','blandit@Nulla.edu','Mi Aliquam Gravida Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Mechelle F. Noble','et.magnis.dis@acnullaIn.org','Phasellus Foundation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Stewart D. Hawkins','fermentum.arcu.Vestibulum@ornare.edu','Sagittis Lobortis PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Halla W. Mayer','Phasellus@orcitincidunt.co.uk','Vestibulum Nec Euismod PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Mercedes U. Wiggins','ipsum.primis.in@feugiat.ca','Nec Imperdiet Nec Company');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Derek G. Franco','feugiat.tellus@quam.edu','Lectus Institute');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Craig L. Mack','sociis.natoque.penatibus@libero.com','Tempor Diam Institute');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Chase P. Frye','Donec.tempor@metus.org','Blandit At Nisi Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Orla T. Lloyd','dictum@convallis.edu','Egestas A Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Sasha Z. Witt','Nam.ac.nulla@vulputate.net','Vulputate Risus A Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Cally P. Adkins','Aliquam@accumsanlaoreetipsum.ca','Tincidunt Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Xander A. Morin','risus.Nunc.ac@Aenean.net','Mi Eleifend Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Salvador K. Rollins','interdum.Curabitur.dictum@egestas.ca','Sodales Elit PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Cassandra E. Berg','Cras.eget.nisi@magnisdis.co.uk','Augue Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Lysandra D. Price','ac@turpisAliquam.org','Diam Nunc Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Denise U. Green','nulla.Integer@pede.edu','Eu Neque Pellentesque PC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Jemima T. Bowman','Curabitur@velit.com','Magnis Corporation');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Elliott L. Park','lobortis.mauris@Maurisvestibulumneque.net','Orci Sem Inc.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Cooper G. Rios','velit.dui.semper@mieleifendegestas.org','Quisque Imperdiet Erat Company');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Kelly X. Whitfield','ipsum.leo@Aeneanegestashendrerit.net','Sapien Nunc Pulvinar Ltd');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Denton G. Adkins','sagittis@ac.com','Donec Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Jarrod J. Andrews','vitae.dolor.Donec@eleifendvitaeerat.ca','Accumsan Convallis Incorporated');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Elizabeth L. Buck','et@tellus.ca','Risus Morbi Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Megan E. Blevins','orci.adipiscing.non@eteuismod.net','Elit Pretium Et Corp.');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Jameson E. Bennett','dis@tinciduntnequevitae.edu','Elit Nulla Facilisi Consulting');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Zorita Z. Pitts','dapibus@lorem.org','Vitae Risus LLC');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Macon P. Hoover','mi.enim@dictum.co.uk','Quisque Limited');
INSERT INTO CONTATO (nome,email,campanha) VALUES ('Samantha I. Barker','Cras.sed.leo@Morbiaccumsanlaoreet.com','Gravida Mauris Incorporated');